// Code generated by hertz generator.

package pixel

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _app_codeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appcodecreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appcodesearchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _handleimgpixeleventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _handlebeaconpixeleventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _app_code0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appcodedetailMw() []app.HandlerFunc {
	// your code...
	return nil
}
